# Generated by Django 2.2 on 2020-09-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plan_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limit',
            field=models.BooleanField(default=False),
        ),
    ]
