# Generated by Django 2.2 on 2020-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plan_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limit',
            field=models.BooleanField(default=True),
        ),
    ]
